### ISSUE TITLE
Final-Capstone-Project : Setup Kanban Board

### ISSUE THREAD

**Issue by tajulafreen** [tajulafreen/Final-capstone-Backend#15]
**Hi code reviewer!**
We are a group of 4:

@tajulafreen 

@kit0-0 

@katfogy 

@DianaBeki 

This is the link to our [Kanban Board](https://github.com/tajulafreen/Final-capstone-Backend/projects/1)

Below is a screenshot of our initial Kanban Board:
![Screenshot (102)](https://github.com/tajulafreen/Final-capstone-Backend/assets/119053190/243d3f4b-155d-4c5c-ad0d-0f231cbc72a8)

**Comment by Meltrust** [comment]
Hi @tajulafreen,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, assignees, and are pointed according to spec.✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
